title: Thermodynamics and Combustion Engineering Laboratory

email:  varuns@iitm.ac.in

description: >
  This lab's goal ... 

timezone: "Asia/Kolkata"
  
<<<<<<< HEAD
baseurl: "" 
url    : "http://example.com"
=======
baseurl: "https://krithikasivaram.github.io/tdce-iitm.github.io/" 
url    : "https://localhost"
>>>>>>> a2238dfafb74ab713692029fd12d5f9fd7eac298

include: ['_pages']

collections:
  news:
  events:
  nptel:
  project:
  research:
  members:
  permalink: /:collection/:path/
  output: true


author:
    name: Krithika Narayanaswamy
