title: Thermodynamics and Combustion Engineering Laboratory

email:  varuns@iitm.ac.in

description: >
  This lab's goal ... 

timezone: "Asia/Kolkata"
  
baseurl: "https://krithikasivaram.github.io/tdce-iitm.github.io/" 
url    : "https://localhost"

include: ['_pages']

collections:
  news:
  events:
  nptel:
  project:
  research:
  members:
    permalink: /:collection/:path/
    output: true


author:
    name: Krithika Narayanaswamy
